export type { LoginSyncClientOptions, RequestOptions } from './client.js'
export type { Credentials } from './credentials.js'
export type { ProtocolVersion } from './detect.js'
export type { LoginSyncErrorCode } from './errors.js'
export type { LoginSyncCookie, LoginSyncPayload } from './payload.js'
export type { DecryptResult, EncryptOptions } from './protocol.js'

export { LoginSyncClient } from './client.js'
export { formatToken, parseToken } from './credentials.js'
export { detectVersion, SUPPORTED_VERSIONS } from './detect.js'
export { isLoginSyncError, LoginSyncError } from './errors.js'
export { decrypt, encrypt } from './protocol.js'
